# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Playing with data every damn day
tagline:          'My journey into data driven journalism. Because every great story starts with a data set'
description:      'Katherine Pennacchio blog'

author:
  name:           'Katherine Pennacchio'
  url:            https://twitter.com/kathypennacchio

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
