# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Playing with data every damn day"
description: > # this means to ignore newlines until "email:"
   Because every great story starts with a data set 

email: kathypennacchio30@gmail.com
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Katherine Pennacchio'
author: 'Katherine Pennacchio'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://ddjeverydamnday.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/kathypennacchio
    desc: Follow me on twitter
    share_url: http://twitter.com/kathypennacchio
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/kathypennacchio
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
